Vagrant.configure("2") do |config|
  config.vm.define "otel" do |c|
    c.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
    c.vm.box = "ubuntu/lunar64"
    c.vm.hostname = "otel"
    c.vm.network "forwarded_port", guest: 8888, host: 8888
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update -q
      apt-get install -yq docker.io docker-compose-v2
      usermod -a -G docker vagrant
      docker pull ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
      docker inspect ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest \
        | jq -r '.[0].GraphDriver.Data.UpperDir' \
        | xargs -i sudo cp {}/telemetrygen /usr/local/bin/
    SHELL
  end
end
