Vagrant.configure("2") do |config|
  config.vm.define "master" do |c|
    c.vm.box = "ubuntu/lunar64"
    c.vm.hostname = "master"
    c.vm.network "private_network", type: "dhcp"
    c.vm.provision "shell", inline: <<-SHELL
      curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg \
        https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
      echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main" \
        | tee /etc/apt/sources.list.d/salt.list
      apt-get update -q
      apt-get install -yq libnss-mdns salt-master salt-minion
      systemctl enable --now salt-master.service
    SHELL
  end

  config.vm.define "minion1" do |c|
    c.vm.box = "ubuntu/lunar64"
    c.vm.hostname = "minion1"
    c.vm.network "private_network", type: "dhcp"
    c.vm.provision "shell", inline: <<-SHELL
      curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg \
        https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
      echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main" \
        | tee /etc/apt/sources.list.d/salt.list
      apt-get update -q
      apt-get install -yq libnss-mdns salt-minion
      echo 'master: master.local' > /etc/salt/minion.d/master.conf
      systemctl restart salt-minion.service
      systemctl enable salt-minion.service
    SHELL
  end

  config.vm.define "minion2" do |c|
    c.vm.box = "ubuntu/lunar64"
    c.vm.hostname = "minion2"
    c.vm.network "private_network", type: "dhcp"
    c.vm.provision "shell", inline: <<-SHELL
      curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg \
        https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
      echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main" \
        | tee /etc/apt/sources.list.d/salt.list
      apt-get update -q
      apt-get install -yq libnss-mdns salt-minion
      echo 'master: master.local' > /etc/salt/minion.d/master.conf
      systemctl restart salt-minion.service
      systemctl enable salt-minion.service
    SHELL
  end
end
