pipeline {
    agent any
    environment {
      PATH = "/var/jenkins_home/go/bin:${env.PATH}"
    }
    stages {
        stage('test') {
            steps {
                sh 'go test'
            }
        }
        stage('build') {
            steps {
                sh 'docker build -t test:$(git rev-parse --short HEAD) .'
            }
        }
        stage('deploy') {
            steps {
                sh 'docker rm -f test'
                sh 'docker run -p 9000:8080 -d --name test test:$(git rev-parse --short HEAD)'
            }
        }
    }
}

