Vagrant.configure("2") do |config|
  config.vm.define "broker1" do |c|
    c.vm.box = "ubuntu/lunar64"
    c.vm.hostname = "broker1"
    c.vm.network "private_network", type: "dhcp"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update -q
      apt-get install -yq libnss-mdns python3-kafka openjdk-17-jre
      mkdir /opt/kafka
      curl https://dlcdn.apache.org/kafka/3.6.1/kafka_2.13-3.6.1.tgz \
        | tar xz --strip-components=1 -C /opt/kafka
      sed -i "/^node.id=/s/=.*/=${HOSTNAME: -1}/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^advertised.listeners=/s/localhost/${HOSTNAME}.local/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^controller.quorum.voters=/s/=.*/=1@broker1.local:9093,2@broker2.local:9093,3@broker3.local:9093/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^offsets.topic.replication.factor=/s/=.*/=2/" \
        /opt/kafka/config/kraft/server.properties
      /opt/kafka/bin/kafka-storage.sh format \
        -t "qk89etSXRw6bZhzLg6QWKA" \
        -c /opt/kafka/config/kraft/server.properties
      systemd-run -p Restart=always -u kafka -E KAFKA_HEAP_OPTS="-Xmx256M -Xms128M" \
        /opt/kafka/bin/kafka-server-start.sh \
        /opt/kafka/config/kraft/server.properties
      echo 'PATH="$PATH:/opt/kafka/bin"' > /etc/profile.d/kafka.sh
    SHELL
  end
  config.vm.define "broker2" do |c|
    c.vm.box = "ubuntu/lunar64"
    c.vm.hostname = "broker2"
    c.vm.network "private_network", type: "dhcp"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update -q
      apt-get install -yq libnss-mdns python3-kafka openjdk-17-jre
      mkdir /opt/kafka
      curl https://dlcdn.apache.org/kafka/3.6.1/kafka_2.13-3.6.1.tgz \
        | tar xz --strip-components=1 -C /opt/kafka
      sed -i "/^node.id=/s/=.*/=${HOSTNAME: -1}/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^advertised.listeners=/s/localhost/${HOSTNAME}.local/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^controller.quorum.voters=/s/=.*/=1@broker1.local:9093,2@broker2.local:9093,3@broker3.local:9093/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^offsets.topic.replication.factor=/s/=.*/=2/" \
        /opt/kafka/config/kraft/server.properties
      /opt/kafka/bin/kafka-storage.sh format \
        -t "qk89etSXRw6bZhzLg6QWKA" \
        -c /opt/kafka/config/kraft/server.properties
      systemd-run -p Restart=always -u kafka -E KAFKA_HEAP_OPTS="-Xmx256M -Xms128M" \
        /opt/kafka/bin/kafka-server-start.sh \
        /opt/kafka/config/kraft/server.properties
      echo 'PATH="$PATH:/opt/kafka/bin"' > /etc/profile.d/kafka.sh
    SHELL
  end
  config.vm.define "broker3" do |c|
    c.vm.box = "ubuntu/lunar64"
    c.vm.hostname = "broker3"
    c.vm.network "private_network", type: "dhcp"
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update -q
      apt-get install -yq libnss-mdns python3-kafka openjdk-17-jre
      mkdir /opt/kafka
      curl https://dlcdn.apache.org/kafka/3.6.1/kafka_2.13-3.6.1.tgz \
        | tar xz --strip-components=1 -C /opt/kafka
      sed -i "/^node.id=/s/=.*/=${HOSTNAME: -1}/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^advertised.listeners=/s/localhost/${HOSTNAME}.local/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^controller.quorum.voters=/s/=.*/=1@broker1.local:9093,2@broker2.local:9093,3@broker3.local:9093/" \
        /opt/kafka/config/kraft/server.properties
      sed -i "/^offsets.topic.replication.factor=/s/=.*/=2/" \
        /opt/kafka/config/kraft/server.properties
      /opt/kafka/bin/kafka-storage.sh format \
        -t "qk89etSXRw6bZhzLg6QWKA" \
        -c /opt/kafka/config/kraft/server.properties
      systemd-run -p Restart=always -u kafka -E KAFKA_HEAP_OPTS="-Xmx256M -Xms128M" \
        /opt/kafka/bin/kafka-server-start.sh \
        /opt/kafka/config/kraft/server.properties
      echo 'PATH="$PATH:/opt/kafka/bin"' > /etc/profile.d/kafka.sh
    SHELL
  end
end
